version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: ruslanlizogub/protractor_e2e
    steps:
      - checkout
      - run: echo "this is the test job"
      - run: yarn install
      - run: ls
      - run: yarn testDefault

# Orchestrate our job run sequence
workflows:
  test_e2e:
    jobs:
      - test