# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1
# Use a package of configuration called an orb.
workflows:
  # Name the workflow "welcome"
  run-e2e-tests-workflow:
    # Run the welcome/run job in its own container
    jobs:
      - e2e_backend:
          name: e2e-api-tests-job
          executor_docker_image: 'circleci/node:14.15.1'
          run_tests_command: "yarn testDefault"
